/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pixel.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PixelModel(props) {
  const { nodes, materials } = useGLTF('/pixel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group2024842135.geometry} material={nodes.group2024842135.material} />
      <mesh geometry={nodes.group1969186587.geometry} material={nodes.group1969186587.material} />
      <mesh geometry={nodes.group436440386.geometry} material={nodes.group436440386.material} />
      <mesh geometry={nodes.group1722548514.geometry} material={nodes.group1722548514.material} />
      <mesh geometry={nodes.group2092306944.geometry} material={nodes.group2092306944.material} />
      <mesh geometry={nodes.group1692842084.geometry} material={nodes.group1692842084.material} />
      <mesh geometry={nodes.group1843945551.geometry} material={nodes.group1843945551.material} />
      <mesh geometry={nodes.group654667833.geometry} material={nodes.group654667833.material} />
      <mesh geometry={nodes.group1216317669.geometry} material={nodes.group1216317669.material} />
      <mesh geometry={nodes.group1453352145.geometry} material={nodes.group1453352145.material} />
      <mesh geometry={nodes.group966987138.geometry} material={nodes.group966987138.material} />
      <mesh geometry={nodes.group270162360.geometry} material={nodes.group270162360.material} />
      <mesh geometry={nodes.group1408118462.geometry} material={nodes.group1408118462.material} />
      <mesh geometry={nodes.group1252760901.geometry} material={nodes.group1252760901.material} />
      <mesh geometry={nodes.group714318018.geometry} material={nodes.group714318018.material} />
      <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
      <mesh geometry={nodes.mesh_6_1.geometry} material={nodes.mesh_6_1.material} />
      <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
      <mesh geometry={nodes.mesh_8_1.geometry} material={nodes.mesh_8_1.material} />
      <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
      <mesh geometry={nodes.mesh_9_1.geometry} material={nodes.mesh_9_1.material} />
      <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
      <mesh geometry={nodes.mesh_11_1.geometry} material={nodes.mesh_11_1.material} />
      <mesh geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} />
      <mesh geometry={nodes.mesh_13_1.geometry} material={nodes.mesh_13_1.material} />
      <mesh geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} />
      <mesh geometry={nodes.mesh_15_1.geometry} material={nodes.mesh_15_1.material} />
      <mesh geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} />
      <mesh geometry={nodes.mesh_20_1.geometry} material={nodes.mesh_20_1.material} />
    </group>
  )
}

useGLTF.preload('/pixel.glb')
